### ISSUE TITLE
getEditTemplate() pluginModel darf nur Variablen enthalten die der Konstruktor von Dialogue konsumiert

### ISSUE THREAD

**Issue by katzlbt** [locandy/dialogue-plugin#11]
pluginModel darf nur verwendet werden um Variablen zu speichern, die permanent sind **und im Konstruktor von Dialogue konsumiert werden**! Alle temporären Variablen dürfen nicht in pluginModel stehen, sondern im scope neben pluginModel!

Folgendes ändern:
  - `pluginModel.importJsonDialogue -> importJsonDialogue`
  - `pluginModel.removeAudioId -> removeAudioId`
  - etc.

**Comment by katzlbt** [comment]
Der fine-uploader pass-through war echt schwer zu lösen, aber nötig. Man kann ja die newAudioId während der Upload läuft ändern oder wenn man anfängt während dem Audio Upload im newImageId Feld zu tippen ... Chaos!

Jetzt bleiben noch ein paar einfache Fälle übrig

**Comment by manuelkuss** [comment]
Durch die Änderung zu temporären Variablen, kann ich die Variablen in den Funktionen nicht mehr setzen. 
z.B. hab ich die Variablen auf "" gesetzt, damit die Felder nach dem Button-Klick wieder leer sind:
Zeile 120 (importJsonDialogue)
Zeile 152 (newDialogueId)
Hast du eine Idee, wie ich das lösen kann?

**Comment by katzlbt** [comment]
Ja. Du steckst die Variablen in ein Array/Map und übergibts das als Parameter an die Funktion. JS übergibt das dann als Referenz anstatt als Wert. zb. inputs = { newDialogueId:"bla", }  ... gleich wie bei pluginModel, nur dass es nicht pluginModel sein soll, weil das persistent ist und die werte in der DB speichert.
