### ISSUE TITLE
Fragen beantworten

### ISSUE THREAD

**Issue by manuelkuss** [locandy/dialogue-plugin#19]
Beantworte bitte meine Fragen in der Datei "fragen.md" im Ordner "dialogue-plugin/doc/"

**Comment by katzlbt** [comment]
Du misbrauchst den Bugtracker ;-) Dann kanst die Fragen gleich hier reintun.

> Quiz1 -> das Inventar wird nicht richtig mit 0 initialisiert: Weißt du was ich falsch gemacht habe?
> Wenn man antwortet kommt eine Fehlermeldung, dass es noch nicht initialisiert ist und mit 0 initialisiert wird. Es funktioniert also prinzipiell, aber die Fehlermeldung soll nicht kommen.
> 

Inventar zeigt Zustände des Spielers an nicht Zustande der Station (du hast i_IQ an der Station angelegt). Du solltest das Plugin "Ziele und Notizen des Spielers" verwenden, das ähnlich funktioniert. Inventar hat Aktionen eincodiert (drop, use) die bei Punkten sinnlos sind. r_ Variablen werden an den Server übertragen, wenn man sich registriert.

> Quiz1 -> Agentbilder können sich nicht nach Score richten. Kann ich das so machen, oder was denkst du dazu?
>    -  Meine Lösung. Ich habe das Image-Plugin verwendet um die Bilder anzeigen zu können, jedoch werden sie ganz groß dargestellt.

Bitte mach's nicht zu kompliziert. Warten wir ab ob wir es so brauchen. Das können wir immer noch nachrüsten, wenn Zeit bleibt. Das Imageplugin ist nur dafür gedacht Vollbilder anzuzeigen. Verkleinern geht nicht.
