### ISSUE TITLE
Antwort: Effekt kann nicht mehr entfernt werden

### ISSUE THREAD

**Issue by katzlbt** [locandy/dialogue-plugin#20]
Auch wenn man im Select auf -- Effect -- stellt wird der Effekt einer Antwort nicht mehr entfernt.

**Comment by manuelkuss** [comment]
Ich habe das Problem nicht reproduzieren können. Bei mir funktioniert es richtig. (Auch wenn ich einen Effekt verwende, der auf Variablen zugreift, die es an diesem Spot nicht gibt, funktioniert es)

Kannst du mir ein konkretes Beispiel dafür geben?

**Comment by katzlbt** [comment]
Scheint jetzt zu funktionieren, vielleicht hat eine andere Änderung das Problem gelöst.
