### ISSUE TITLE
Add Image: Upload von jpeg geht nicht

### ISSUE THREAD

**Issue by katzlbt** [locandy/dialogue-plugin#23]
Wenn man ein jpeg als Bild rauflädt verschwindet es (inklusive ID) nach dem Upload. Es ist im Array der resourcen drin, aber wird nicht in drop-downs angezeigt. Auch gifs testen!

**Comment by katzlbt** [comment]
Hast du das getestet? Das schaut mir nicht nach einem korrekten if in Javascript aus ...
`value.mimetype=='image/png' || 'image/jpeg' || 'image/gif'`
sollte es nicht so gehen ... ?
`value.mimetype=='image/png' || value.mimetype=='image/jpeg' || value.mimetype=='image/gif'`

**Comment by manuelkuss** [comment]
Ich habe es getestet, und auch gerade nochmals.

Aber stimmt: Ich wunder mich gerade auch, warum das funktioniert. Sollte es eigentlich nicht...

**Comment by katzlbt** [comment]
"c" == "a" || "b" Hat das Resultat "b" und das ist immer wahr, weil kein Leerstring. JavaScrit ist da in mancher Beziehung etwas komisch. Es sollten jetzt bei den Bildern auch Sounds angezeigt werden.
