### ISSUE TITLE
Audio/Image Upload mit existierender ID ist möglich

### ISSUE THREAD

**Issue by katzlbt** [locandy/dialogue-plugin#24]
Folgende Fehler treten auf:
Der Image/Audio Upload Button ist aktiviert wenn eine existierende resourceID im Textfeld steht **Sounds mit gleichem Namen können Bilder mit gleichem Namen überschreiben!** Das muss unbedingt vermieden werden, weil das den Dialog zerstört. Ich habe jetzt einen Check ganz spät eingebaut, also nach dem Upload, der Überschreiben verhindert. Aber das ist user-unfreundlich.

Wie könnte man das lösen?

**Comment by katzlbt** [comment]
a8a2583 verhindert überschreiben nach upload

**Comment by manuelkuss** [comment]
Wie findest du diese Lösung? 7df945d Ich habe noch eine Überpfüfung bei ng-disabled eingefügt. Damit kann man gar nicht den Upload-button drücken, wenn man eine id schon vergeben hat. (Vielleicht dazu noch eine Info für den User, dass es diese Id schon gibt?)

`ng-disabled="readOnly || (pluginModel.resources[newImageId] !== undefined) || newImageId == null || newImageId == \'\'"\`

**Comment by katzlbt** [comment]
Ja das sollte so passen.
