### ISSUE TITLE
Portrait Größe soll änderbar sein

### ISSUE THREAD

**Issue by katzlbt** [locandy/dialogue-plugin#4]
<img width="391" alt="Bildschirmfoto 2020-01-21 um 10 22 26" src="https://user-images.githubusercontent.com/260347/72791958-7b23cb80-3c38-11ea-9dd1-8deb8cecc5fe.png">

Also hier neben dem Bild ein Textfeld "Image width:" einbauen, mit dem man die Bildgröße(HÖHE) wählen kann. Z.B. 150px, 200px, 300px (min. = 100, max ist 300). Die Breite soll der Browser automatisch setzen (umgekehrt wie bisher die width:33%).

Der Default ist LEER (undefined), die Größe wird in der Instanzvariable `Dialogue plugin.imageHeight` gespeichert. Konstruktor Default ist 150. Wenn eine Höhe durch einen DialogueTree-Knoten via JSON `imageHeight` gesetzt wurde gilt die für alle folgenden Dialoge bis sie wieder geändert wird.

**Comment by manuelkuss** [comment]
Also muss ich eine Variable neben der imageId anlegen? so: dialogue[activeDialogueId].imageHeight

Und dann diesen Wert in eine Globale Variable plugin.imageHeight übernehmen? Somit wird die Höhe nur geändert, wenn eine Höhe angegeben wurde (weil dann der Wert der globalen Variable überschrieben wird).

Ist das so richtig?

**Comment by katzlbt** [comment]
Ja du hast es verstanden. Nur ist plugin.imageHeight eine Variable einer Instanz (Instanzvariable) der Klasse Dialogue und keine globale Variable und auch keine statische Variable (Klassenvariable). Siehe z.B. hier: https://mein-javablog.de/java-klassenvariablen/

**Comment by manuelkuss** [comment]
**css-Problem:** 
Wenn ich die height im img-tag ändern will funktioniert das nicht. Die folgenden css-Stylings überschrieben meine gesetzte Höhe mit auto:

- #player img { ... height:auto; ...}

- .img-responsive, .thumbnail>img, .thumbnail a>img, .carousel-inner>.item>img, .carousel-inner>.item>a>img { ... height:auto; ... }

Um das zu Beheben bräuchte ich Zugriff auf die css-Datei. Inline kann ich da leider nichts machen.
(Es funktioniert zum testen, wenn ich im Chrome die css-Bereiche ausblende.)

Kann ich dir am Donnerstag dann zeigen, wenn du Zeit hast.

**Comment by katzlbt** [comment]
Dann nehmen wir einfach `imageWidth` wenn das geht. Ist eigentlich eh dasselbe. 
`ng-style="{'width':plugin.imageWith}"` oder so ähnlich! -- übrigens hat style= höhere Priorität als class.

**Comment by katzlbt** [comment]
Das muss noch gerichtet werden: ng-style="{\'**width**\':plugin.**imageHeight**}" Also musst du imageHeight des Plugins und Modells in imageWidth umbenennen!

**Comment by manuelkuss** [comment]
Habs geändert.
Kann ich den width-Bereicht von 100-300 auf 80-280 ändern?
(300 geht über den Rand hinaus, und 100 ist schon recht groß)

**Comment by katzlbt** [comment]
Sicher.
